import json
import os
import random
import re
import time
from typing import Any, Dict, List, Optional

from dotenv import load_dotenv
from google import genai
from google.genai import types

from gemini_usage import record_usage


load_dotenv()


# ============================================================
# CONFIGURATION
# ============================================================

API_KEY = os.getenv("GEMINI_API_KEY")

MODEL = os.getenv("GEMINI_MODEL", "gemini-3.6-flash")

# Application-level retry:
# 0 = one total request
# 1 = initial request + one retry
MAX_RETRIES = 1

# Base delay before retry.
RETRY_DELAY_SECONDS = 2


# ============================================================
# VALIDATION
# ============================================================

if not API_KEY:
    raise RuntimeError(
        "GEMINI_API_KEY is missing. Add it to your .env file."
    )


# ============================================================
# GEMINI CLIENT
# ============================================================

# Disable SDK's built-in multiple retries.
#
# We handle retries ourselves so QuantIQ has predictable behavior:
#
# Attempt 1 -> Gemini
#        |
#        +-- success -> continue
#        |
#        +-- transient 503/429/5xx -> wait -> Attempt 2
#        |
#        +-- permanent error -> fail immediately
#
client = genai.Client(
    api_key=API_KEY,
    http_options=types.HttpOptions(
        retry_options=types.HttpRetryOptions(
            attempts=1
        )
    )
)


# ============================================================
# TRANSIENT ERROR DETECTION
# ============================================================

def is_transient_error(error: Exception) -> bool:
    """
    Return True only for errors where retrying may reasonably help.

    Retry:
        408
        429
        500
        502
        503
        504
        RESOURCE_EXHAUSTED
        UNAVAILABLE
        INTERNAL
        DEADLINE_EXCEEDED

    Do NOT retry:
        400
        401
        403
        invalid API key
        malformed request
        invalid JSON generated by the model
        schema/planner validation problems
        other permanent client-side errors
    """

    error_text = str(error).upper()

    transient_markers = [
        "408",
        "429",
        "500",
        "502",
        "503",
        "504",
        "RESOURCE_EXHAUSTED",
        "UNAVAILABLE",
        "INTERNAL",
        "DEADLINE_EXCEEDED",
        "TIMEOUT",
        "TIMED OUT",
    ]

    return any(marker in error_text for marker in transient_markers)


# ============================================================
# JSON EXTRACTION
# ============================================================

def extract_json(text: str) -> Dict[str, Any]:
    """
    Extract a JSON object from Gemini's response.

    Handles:
    - pure JSON
    - ```json ... ```
    - accidental surrounding text
    """

    if not text:
        raise ValueError("Gemini returned an empty response.")

    cleaned = text.strip()

    # Remove markdown fences.
    cleaned = re.sub(
        r"^```(?:json)?\s*",
        "",
        cleaned,
        flags=re.IGNORECASE
    )

    cleaned = re.sub(
        r"\s*```$",
        "",
        cleaned
    )

    cleaned = cleaned.strip()

    # First try direct parsing.
    try:
        parsed = json.loads(cleaned)

        if not isinstance(parsed, dict):
            raise ValueError(
                "Gemini returned JSON, but the root value is not an object."
            )

        return parsed

    except json.JSONDecodeError:
        pass

    # Try finding the first JSON object inside surrounding text.
    start = cleaned.find("{")

    if start == -1:
        raise ValueError(
            "Could not find a JSON object in Gemini's response."
        )

    decoder = json.JSONDecoder()

    try:
        parsed, _ = decoder.raw_decode(cleaned[start:])
    except json.JSONDecodeError as exc:
        raise ValueError(
            f"Gemini returned invalid JSON: {exc}"
        ) from exc

    if not isinstance(parsed, dict):
        raise ValueError(
            "Gemini returned JSON, but the root value is not an object."
        )

    return parsed


# ============================================================
# GENERIC HELPERS
# ============================================================

def ensure_list(value: Any) -> List[Any]:
    """
    Convert None/single values into a list.
    """

    if value is None:
        return []

    if isinstance(value, list):
        return value

    return [value]


def clean_string(value: Any) -> str:
    if value is None:
        return ""

    return str(value).strip()


def normalize_identifier(value: Any) -> str:
    """
    Normalize SQL identifiers for comparison only.

    This does NOT change the identifier returned to the SQL generator.
    """

    text = clean_string(value)

    text = text.strip()

    if text.startswith("`") and text.endswith("`"):
        text = text[1:-1]

    if text.startswith('"') and text.endswith('"'):
        text = text[1:-1]

    if text.startswith("[") and text.endswith("]"):
        text = text[1:-1]

    return text.strip().lower()


def normalize_column_reference(value: Any) -> str:
    """
    Normalize table.column style references.
    """

    text = clean_string(value)

    text = text.replace("`", "")
    text = text.replace('"', "")
    text = text.replace("[", "")
    text = text.replace("]", "")

    return text.strip().lower()


# ============================================================
# SCHEMA RELATIONSHIP EXTRACTION
# ============================================================

def extract_schema_relationships(schema_context: str) -> List[Dict[str, str]]:
    """
    Extract FK relationships from the schema context.

    Expected schema lines can look like:

        - "inventory"."film_id" -> "film"."film_id"

    or:

        - inventory.film_id -> film.film_id

    This is only used to validate Gemini's proposed joins.
    """

    relationships: List[Dict[str, str]] = []

    if not schema_context:
        return relationships

    lines = schema_context.splitlines()

    for line in lines:
        if "->" not in line:
            continue

        left, right = line.split("->", 1)

        left = normalize_column_reference(left)
        right = normalize_column_reference(right)

        # Remove prefixes such as:
        # FOREIGN KEY RELATIONSHIPS:
        # -
        left = left.lstrip("- ").strip()
        right = right.lstrip("- ").strip()

        if "." not in left or "." not in right:
            continue

        relationships.append(
            {
                "left": left,
                "right": right
            }
        )

    return relationships


def relationship_exists(
    left_table: str,
    left_column: str,
    right_table: str,
    right_column: str,
    relationships: List[Dict[str, str]]
) -> bool:
    """
    Check whether a proposed join exists in the discovered schema.

    The direction is treated as irrelevant because:

        A.x -> B.x

    and

        B.x -> A.x

    represent the same relationship.
    """

    proposed_left = (
        f"{normalize_identifier(left_table)}."
        f"{normalize_identifier(left_column)}"
    )

    proposed_right = (
        f"{normalize_identifier(right_table)}."
        f"{normalize_identifier(right_column)}"
    )

    for relationship in relationships:
        schema_left = relationship["left"]
        schema_right = relationship["right"]

        if (
            proposed_left == schema_left
            and proposed_right == schema_right
        ):
            return True

        if (
            proposed_left == schema_right
            and proposed_right == schema_left
        ):
            return True

    return False


# ============================================================
# JOIN NORMALIZATION
# ============================================================

def normalize_joins(
    joins: Any,
    schema_context: str
) -> List[Dict[str, str]]:
    """
    Normalize and validate Gemini's JOIN definitions.

    Invalid/invented relationships are rejected instead of silently
    allowing Gemini to invent database relationships.
    """

    relationships = extract_schema_relationships(schema_context)

    normalized: List[Dict[str, str]] = []

    for join in ensure_list(joins):

        if not isinstance(join, dict):
            continue

        left_table = clean_string(
            join.get("left_table")
        )

        left_column = clean_string(
            join.get("left_column")
        )

        right_table = clean_string(
            join.get("right_table")
        )

        right_column = clean_string(
            join.get("right_column")
        )

        if not all(
            [
                left_table,
                left_column,
                right_table,
                right_column,
            ]
        ):
            continue

        # If FK relationships were found, only accept joins
        # represented in the discovered schema.
        if relationships:

            if not relationship_exists(
                left_table,
                left_column,
                right_table,
                right_column,
                relationships,
            ):
                raise ValueError(
                    "Gemini proposed a JOIN that does not exist "
                    f"in the discovered schema: "
                    f"{left_table}.{left_column} = "
                    f"{right_table}.{right_column}"
                )

        normalized.append(
            {
                "left_table": left_table,
                "left_column": left_column,
                "right_table": right_table,
                "right_column": right_column,
            }
        )

    return normalized


# ============================================================
# ANALYSIS NORMALIZATION
# ============================================================

def normalize_filters(filters: Any) -> List[Dict[str, Any]]:
    """
    Normalize filters without hardcoding dataset-specific fields.
    """

    normalized = []

    for item in ensure_list(filters):

        if not isinstance(item, dict):
            continue

        column = clean_string(
            item.get("column")
        )

        operator = clean_string(
            item.get("operator")
        ).upper()

        value = item.get("value")

        if not column or not operator:
            continue

        normalized.append(
            {
                "column": column,
                "operator": operator,
                "value": value,
            }
        )

    return normalized


def normalize_sort(sort: Any) -> List[Dict[str, str]]:
    """
    Normalize sorting definitions.
    """

    normalized = []

    for item in ensure_list(sort):

        if not isinstance(item, dict):
            continue

        column = clean_string(
            item.get("column")
        )

        direction = clean_string(
            item.get("direction", "DESC")
        ).upper()

        if not column:
            continue

        if direction not in {"ASC", "DESC"}:
            direction = "DESC"

        normalized.append(
            {
                "column": column,
                "direction": direction,
            }
        )

    return normalized


def normalize_output_columns(value: Any) -> List[str]:
    """
    Normalize columns that should appear in ordinary row/list queries.

    This is intentionally generic. Nothing is hardcoded.
    """

    result = []

    for item in ensure_list(value):

        if isinstance(item, str):
            column = item.strip()

        elif isinstance(item, dict):
            column = clean_string(
                item.get("column")
                or item.get("name")
            )

        else:
            continue

        if column:
            result.append(column)

    return result


def normalize_analysis(
    analysis: Dict[str, Any],
    schema_context: str
) -> Dict[str, Any]:
    """
    Normalize one analysis object while preserving the planner's
    dynamic structure.
    """

    result: Dict[str, Any] = {}

    # --------------------------------------------------------
    # Intent
    # --------------------------------------------------------

    result["intent"] = clean_string(
        analysis.get("intent")
    )

    # --------------------------------------------------------
    # Metric
    # --------------------------------------------------------

    metric = analysis.get("metric")

    if metric is None:
        result["metric"] = None
    else:
        result["metric"] = clean_string(metric)

    # --------------------------------------------------------
    # Dimension
    # --------------------------------------------------------

    dimension = analysis.get("dimension")

    if dimension is None:
        result["dimension"] = None
    else:
        result["dimension"] = clean_string(dimension)

    # --------------------------------------------------------
    # Aggregation
    # --------------------------------------------------------

    aggregation = clean_string(
        analysis.get("aggregation")
    ).upper()

    if not aggregation:
        aggregation = "NONE"

    result["aggregation"] = aggregation

    # --------------------------------------------------------
    # Tables
    # --------------------------------------------------------

    tables = []

    for table in ensure_list(
        analysis.get("tables")
    ):

        table_name = clean_string(table)

        if table_name:
            tables.append(table_name)

    result["tables"] = tables

    # --------------------------------------------------------
    # Joins
    # --------------------------------------------------------

    result["joins"] = normalize_joins(
        analysis.get("joins", []),
        schema_context,
    )

    # --------------------------------------------------------
    # Filters
    # --------------------------------------------------------

    result["filters"] = normalize_filters(
        analysis.get("filters", [])
    )

    # --------------------------------------------------------
    # Output columns
    # --------------------------------------------------------

    result["output_columns"] = normalize_output_columns(
        analysis.get("output_columns", [])
    )

    # --------------------------------------------------------
    # Group by
    # --------------------------------------------------------

    group_by = []

    for column in ensure_list(
        analysis.get("group_by")
    ):

        column_name = clean_string(column)

        if column_name:
            group_by.append(column_name)

    result["group_by"] = group_by

    # --------------------------------------------------------
    # Sort
    # --------------------------------------------------------

    result["sort"] = normalize_sort(
        analysis.get("sort", [])
    )

    # --------------------------------------------------------
    # Limit
    # --------------------------------------------------------

    limit = analysis.get("limit")

    if limit is None:
        result["limit"] = None

    else:
        try:
            result["limit"] = int(limit)
        except (ValueError, TypeError):
            result["limit"] = None

    # --------------------------------------------------------
    # Having
    # --------------------------------------------------------

    result["having"] = normalize_filters(
        analysis.get("having", [])
    )

    # --------------------------------------------------------
    # Ranking
    # --------------------------------------------------------

    ranking = analysis.get("ranking")

    if isinstance(ranking, dict):

        result["ranking"] = {
            "enabled": bool(
                ranking.get("enabled", False)
            ),
            "column": clean_string(
                ranking.get("column")
            ),
            "direction": clean_string(
                ranking.get(
                    "direction",
                    "DESC"
                )
            ).upper(),
        }

    else:
        result["ranking"] = {
            "enabled": False,
            "column": "",
            "direction": "DESC",
        }

    # --------------------------------------------------------
    # Keep additional planner metadata
    # --------------------------------------------------------

    for key in [
        "question",
        "description",
        "comparison",
        "time_grain",
        "date_column",
        "value",
    ]:

        if key in analysis:
            result[key] = analysis[key]

    return result


# ============================================================
# PLAN NORMALIZATION
# ============================================================

def normalize_plan(
    plan: Dict[str, Any],
    schema_context: str
) -> Dict[str, Any]:
    """
    Normalize the entire Gemini planner response.
    """

    if not isinstance(plan, dict):
        raise ValueError(
            "Gemini planner response must be a JSON object."
        )

    normalized: Dict[str, Any] = {}

    # --------------------------------------------------------
    # Main question
    # --------------------------------------------------------

    normalized["question"] = clean_string(
        plan.get("question")
    )

    # --------------------------------------------------------
    # Intent
    # --------------------------------------------------------

    normalized["intent"] = clean_string(
        plan.get("intent")
    )

    # --------------------------------------------------------
    # Tables
    # --------------------------------------------------------

    tables = []

    for table in ensure_list(
        plan.get("tables")
    ):

        table_name = clean_string(table)

        if table_name:
            tables.append(table_name)

    normalized["tables"] = tables

    # --------------------------------------------------------
    # Global joins
    # --------------------------------------------------------

    normalized["joins"] = normalize_joins(
        plan.get("joins", []),
        schema_context,
    )

    # --------------------------------------------------------
    # Analyses
    # --------------------------------------------------------

    raw_analyses = plan.get("analyses")

    if raw_analyses is None:

        # Support a single-analysis planner response.
        raw_analyses = [plan]

    elif isinstance(raw_analyses, dict):

        raw_analyses = [raw_analyses]

    elif not isinstance(raw_analyses, list):

        raise ValueError(
            "Planner field 'analyses' must be an array."
        )

    analyses = []

    for raw_analysis in raw_analyses:

        if not isinstance(raw_analysis, dict):
            continue

        analysis = normalize_analysis(
            raw_analysis,
            schema_context,
        )

        analyses.append(analysis)

    if not analyses:
        raise ValueError(
            "Gemini planner returned no usable analyses."
        )

    normalized["analyses"] = analyses

    # --------------------------------------------------------
    # Optional planner metadata
    # --------------------------------------------------------

    if "reasoning" in plan:
        normalized["reasoning"] = clean_string(
            plan.get("reasoning")
        )

    if "notes" in plan:
        normalized["notes"] = clean_string(
            plan.get("notes")
        )

    return normalized


# ============================================================
# PROMPT
# ============================================================

def build_planner_prompt(
    question: str,
    schema_context: str,
    conversation_context: str = ""
) -> str:
    """
    Build the dynamic planner prompt.

    No dataset-specific table names, columns, questions,
    answers, or business rules are hardcoded.
    """

    conversation_section = ""

    if conversation_context.strip():

        conversation_section = f"""
CONVERSATION CONTEXT
====================

The user may be asking a follow-up question.

Use the previous conversation to resolve references such as:

- "that month"
- "that region"
- "the same period"
- "those customers"
- "it"
- "them"
- "the previous result"
- "top 5 for that month"

Do not blindly repeat an earlier query.

Determine what the current question means using the
conversation context together with the database schema.

Previous conversation:

{conversation_context}

END CONVERSATION CONTEXT
========================
"""

    prompt = f"""
You are the database planning engine for QuantIQ,
an AI-powered data analyst.

Your job is to convert the user's natural-language question
into a structured database analysis plan.

You are NOT the SQL executor.

You must return ONLY valid JSON.

============================================================
USER QUESTION
============================================================

{question}

============================================================
DATABASE SCHEMA
============================================================

{schema_context}

{conversation_section}

============================================================
PLANNING RULES
============================================================

1. Use ONLY tables and columns that exist in the supplied schema.

2. Never invent:
   - tables
   - columns
   - relationships
   - metrics
   - values
   - joins

3. Use foreign-key relationships from the schema when joins
   are required.

4. If multiple tables are required, populate the "tables"
   field and the "joins" field.

5. Every required relationship must be represented explicitly.

6. For joined columns, prefer:
       table.column

7. Understand natural language dynamically.

8. Do not assume that the database is a sales database.

9. The same planner must work for:
   - retail
   - finance
   - HR
   - healthcare
   - movies
   - payments
   - inventory
   - customers
   - products
   - any other relational dataset

10. Do not hardcode a particular question or answer.

============================================================
ANALYSIS TYPES
============================================================

The question may require one or more analyses.

Examples of conceptual analysis types include:

- single aggregate
- grouped aggregate
- comparison
- ranking
- filtered ranking
- row/list retrieval
- time-based analysis
- trend analysis
- percentage
- ratio
- average
- count
- sum
- minimum
- maximum
- explanation/diagnostic analysis

When the question requires multiple calculations,
create multiple objects inside "analyses".

============================================================
ORDINARY ROW / LIST QUESTIONS
============================================================

For questions asking for actual records or entity lists,
do NOT invent a metric.

Use:

"aggregation": "NONE"

and provide the required fields through:

"output_columns"

Example structure:

"output_columns": [
    "table.column_a",
    "table.column_b"
]

Only include columns that are actually needed to answer
the user's question.

============================================================
AGGREGATION
============================================================

Supported conceptual aggregation values may include:

- NONE
- SUM
- AVG
- COUNT
- MIN
- MAX

Use the aggregation that matches the question.

If no aggregation is needed, use:

"aggregation": "NONE"

============================================================
GROUPING
============================================================

For grouped questions, populate:

"group_by"

For example, conceptually:

"group_by": [
    "table.region"
]

Do not hardcode region or any other particular dimension.

============================================================
FILTERS
============================================================

Represent conditions using:

"filters": [
    {{
        "column": "table.column",
        "operator": "...",
        "value": ...
    }}
]

Possible operators include:

- =
- !=
- >
- >=
- <
- <=
- IN
- NOT IN
- LIKE
- NOT LIKE
- IS NULL
- IS NOT NULL

Use the operator that matches the user's language.

============================================================
HAVING
============================================================

Conditions applied AFTER aggregation must be represented
inside:

"having"

Do not incorrectly put aggregate conditions into WHERE filters.

For example, if the user asks for entities whose total
revenue is greater than a threshold, the threshold belongs
in HAVING after grouping.

============================================================
RANKING
============================================================

For ranking questions, use:

"ranking": {{
    "enabled": true,
    "column": "...",
    "direction": "DESC"
}}

For "top" use DESC.

For "bottom" use ASC.

Populate "limit" when the user gives a number.

============================================================
SORTING
============================================================

Use:

"sort": [
    {{
        "column": "...",
        "direction": "DESC"
    }}
]

Do not invent columns.

============================================================
TIME QUESTIONS
============================================================

For date/time questions, identify the appropriate date column
from the schema.

Use:

"date_column"

when useful.

Use:

"time_grain"

when the user requests a period such as:

- day
- week
- month
- quarter
- year

Do not assume a date column without schema evidence.

============================================================
COMPARISONS
============================================================

If the question compares multiple entities, periods,
dimensions, or metrics, create the necessary analyses.

Do not force everything into one analysis if multiple
calculations are required.

============================================================
DIAGNOSTIC / WHY QUESTIONS
============================================================

For questions such as:

"Why did X decrease?"

"Why is A lower than B?"

"Why is profit lower?"

Do not invent a causal explanation.

Create analyses that retrieve measurable evidence
needed to investigate the difference.

The final answer will be generated only from actual
database results.

============================================================
OUTPUT FORMAT
============================================================

Return exactly this general JSON structure:

{{
    "question": "...",
    "intent": "...",
    "tables": [
        "..."
    ],
    "joins": [
        {{
            "left_table": "...",
            "left_column": "...",
            "right_table": "...",
            "right_column": "..."
        }}
    ],
    "analyses": [
        {{
            "intent": "...",
            "metric": "...",
            "dimension": "...",
            "aggregation": "NONE",
            "tables": [
                "..."
            ],
            "joins": [],
            "output_columns": [],
            "filters": [],
            "having": [],
            "group_by": [],
            "sort": [],
            "limit": null,
            "ranking": {{
                "enabled": false,
                "column": "",
                "direction": "DESC"
            }}
        }}
    ]
}}

IMPORTANT:

- Return JSON only.
- Do not use Markdown.
- Do not explain the JSON.
- Do not include SQL.
- Do not invent schema elements.
- Do not answer the user's question directly.
- Build the plan dynamically from the supplied schema and
  conversation context.
"""

    return prompt


# ============================================================
# GEMINI CALL
# ============================================================

def _call_gemini(
    prompt: str
):
    """
    Make exactly one Gemini SDK request.

    SDK-level retries are disabled in the client configuration.
    """

    response = client.models.generate_content(
        model=MODEL,
        contents=prompt,
        config=types.GenerateContentConfig(
            response_mime_type="application/json"
        ),
    )

    # Preserve QuantIQ token tracking.
    record_usage(
        response=response,
        call_type="planner"
    )

    return response


# ============================================================
# CREATE PLAN
# ============================================================

def create_plan(
    question: str,
    schema_context: str,
    conversation_context: str = "",
    max_retries: int = MAX_RETRIES,
) -> Dict[str, Any]:
    """
    Create a structured analysis plan using Gemini.

    Retry behavior:

        max_retries = 0
            -> 1 total Gemini request

        max_retries = 1
            -> maximum 2 total Gemini requests

    Only transient Gemini/service errors are retried.
    """

    question = clean_string(question)

    if not question:
        raise ValueError(
            "Question cannot be empty."
        )

    if not schema_context or not schema_context.strip():
        raise ValueError(
            "Schema context cannot be empty."
        )

    prompt = build_planner_prompt(
        question=question,
        schema_context=schema_context,
        conversation_context=conversation_context,
    )

    # Prevent accidental negative values.
    try:
        max_retries = max(0, int(max_retries))
    except (TypeError, ValueError):
        max_retries = MAX_RETRIES

    total_attempts = max_retries + 1

    last_error: Optional[Exception] = None

    for attempt in range(total_attempts):

        try:

            response = _call_gemini(prompt)

            response_text = getattr(
                response,
                "text",
                None
            )

            if not response_text:
                raise ValueError(
                    "Gemini returned no text."
                )

            raw_plan = extract_json(
                response_text
            )

            normalized_plan = normalize_plan(
                raw_plan,
                schema_context,
            )

            return normalized_plan

        except ValueError:
            # Planner validation errors and invalid JSON are
            # not transient Gemini service errors.
            #
            # Retrying the exact same invalid response does not
            # solve the underlying planning problem.
            raise

        except Exception as error:

            last_error = error

            transient = is_transient_error(
                error
            )

            retries_remaining = (
                attempt < max_retries
            )

            if not transient or not retries_remaining:

                raise RuntimeError(
                    "Gemini planner failed after "
                    f"{attempt + 1} total attempt(s): "
                    f"{error}"
                ) from error

            # ------------------------------------------------
            # Exponential backoff + jitter
            # ------------------------------------------------

            delay = (
                RETRY_DELAY_SECONDS
                * (2 ** attempt)
            )

            jitter = random.uniform(
                0,
                0.75
            )

            total_delay = (
                delay + jitter
            )

            print(
                "[Gemini Planner] "
                f"Transient error detected "
                f"(attempt {attempt + 1}/{total_attempts}): "
                f"{error}"
            )

            print(
                "[Gemini Planner] "
                f"Retrying once after "
                f"{total_delay:.2f}s..."
            )

            time.sleep(
                total_delay
            )

    # This should not normally be reached.
    raise RuntimeError(
        "Gemini planner failed."
        + (
            f" Last error: {last_error}"
            if last_error
            else ""
        )
    )


# ============================================================
# SIMPLE TEST
# ============================================================

if __name__ == "__main__":

    print("=" * 70)
    print("QuantIQ Gemini Planner")
    print("=" * 70)

    print(f"Model: {MODEL}")
    print(
        "Maximum total Gemini attempts: "
        f"{MAX_RETRIES + 1}"
    )

    print()
    print(
        "This module is intended to be imported by "
        "QuantIQ's FastAPI backend."
    )